travis:
  secure:
    BINSTAR_TOKEN: mMFEaktp3YFerFWVgFLYHn0a92s4zqFKwVHDeNOCOo7tMtMxxiNQZFSiBlXzx+yVFE1FV623JUeWbRA4ckNH8tXUQvgPEFQ59IthhG7gQAh3Vopz89uJ2htl4A52nqlMLOAdUa004OLja3/8utd8hiW8AeahQ1KjCppw5n3zP9sBMT1estyhSHDBSNUj3pcA73tVCEnpYs6Gj+yORs+zPYnskKgFT4IPSj0+NutRgaNnP+ZCqDxsAdjzVq9kPQVQspl5I7mZDsJ7CGIyQKpSBdfAHz+9/Xss3BiB6qj97fzb0bsKGtTpGicPaHvG/65+7Tmb+hTkB9kqOxkGB07v/taKIHnoC0bXE3nPfZ5ZlIS+extfi/QpRqaYMgowu9Y4MmYSJYaKoQhsB9TIMVveOtSad3NyuBGC8KR83IMRC8hLQOGMWI6sLEd2FwIkXHWU2Q51Z6JjcPzr9tezA9mfKkKASEFN1ChrLKQx6shV5LkwQMjKI40jjokRAisVLvUNLKamlm0yOQlV+pn+nvJhHIA0CDgZxwwJQcqjiATL/NTMUZwcHv0nmO1BhZm67OnNZzmYxRMFPlW7PHvnX03Gk0LjQmSuKZO1Sa63d2PtwtI0QgJllFjwP+BfpVAGC+qYUxq9O/QeTm9VyAdoC89AP6rf17VIozbsEXo4JOKbkf4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
